# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: cimg/node:17.2.0
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      
workflows:
  build:
    jobs:
      - build-medium

